---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  vars_files:
    - ../../configs/vault.yml
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  vars_files:
    - ../../configs/vault.yml
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  vars_files:
  #  - vault.yml
    - ../../configs/vault.yml
  roles:
    - role: k3s_agent

#- name: Install and configure Rancher
#  hosts: server
#  become: true
#  vars_files:
#    - vault.yml
#  roles:
#    - role: rancher
